import pool from "../utils/db.js";
import type { Pool, ResultSetHeader, RowDataPacket } from "mysql2/promise";
import type { Category, Priority, Status, TicketInput, TicketRow } from "../types/index.js";
interface TicketPacket extends RowDataPacket, TicketRow {}
interface CountPacket extends RowDataPacket { total:number; }
export interface TicketFilters { search?:string; status?:Status; priority?:Priority; category?:Category; agentId?:number; sort?:string; page:number; limit:number; }
const base=`SELECT t.id,t.customer_id,c.name customer_name,c.email customer_email,t.agent_id,a.name agent_name,t.subject,t.description,t.priority,t.category,t.status,t.created_at,t.updated_at FROM tickets t JOIN customers c ON c.id=t.customer_id LEFT JOIN agents a ON a.id=t.agent_id`;
export async function listTickets(f:TicketFilters){const where:string[]=[];const params:(string|number)[]=[];if(f.search){where.push("(c.name LIKE ? OR c.email LIKE ? OR t.subject LIKE ?)");const s=`%${f.search}%`;params.push(s,s,s)}if(f.status){where.push("t.status=?");params.push(f.status)}if(f.priority){where.push("t.priority=?");params.push(f.priority)}if(f.category){where.push("t.category=?");params.push(f.category)}if(f.agentId){where.push("t.agent_id=?");params.push(f.agentId)}const clause=where.length?` WHERE ${where.join(" AND ")}`:"";let order="t.created_at DESC";if(f.sort==="oldest")order="t.created_at ASC";if(f.sort==="priority")order=`FIELD(t.priority,'CRITICAL','HIGH','MEDIUM','LOW'), t.created_at DESC`;const offset=(f.page-1)*f.limit;const [rows]=await pool.query<TicketPacket[]>(`${base}${clause} ORDER BY ${order} LIMIT ? OFFSET ?`,[...params,f.limit,offset]);const [count]=await pool.query<CountPacket[]>(`SELECT COUNT(*) total FROM tickets t JOIN customers c ON c.id=t.customer_id${clause}`,params);return {data:rows,page:f.page,limit:f.limit,total:Number(count[0]?.total??0),totalPages:Math.ceil(Number(count[0]?.total??0)/f.limit)};}
export async function getTicket(id:number){const [rows]=await pool.query<TicketPacket[]>(`${base} WHERE t.id=?`,[id]);return rows[0]??null}
export async function createTicket(input:TicketInput){const conn=await pool.getConnection();try{await conn.beginTransaction();const [existing]=await conn.query<RowDataPacket[]>("SELECT id FROM customers WHERE email=? LIMIT 1",[input.email]);let customerId:number;if(existing.length){customerId=Number(existing[0].id);await conn.execute("UPDATE customers SET name=? WHERE id=?",[input.name,customerId])}else{const [r]=await conn.execute<ResultSetHeader>("INSERT INTO customers(name,email) VALUES(?,?)",[input.name,input.email]);customerId=r.insertId}const [r]=await conn.execute<ResultSetHeader>("INSERT INTO tickets(customer_id,subject,description,priority,category,status) VALUES(?,?,?,?,?,'OPEN')",[customerId,input.subject,input.description,input.priority,input.category]);await conn.commit();return getTicket(r.insertId)}catch(e){await conn.rollback();throw e}finally{conn.release()}}
export async function updateTicket(id:number,data:Partial<Pick<TicketInput,"subject"|"description"|"priority"|"category">>){const fields:string[]=[];const values:(string|number)[]=[];for(const key of ["subject","description","priority","category"] as const){if(data[key]!==undefined){fields.push(`${key}=?`);values.push(data[key] as string)}}if(!fields.length)return getTicket(id);values.push(id);const [r]=await pool.execute<ResultSetHeader>(`UPDATE tickets SET ${fields.join(", ")} WHERE id=?`,values);if(!r.affectedRows)return null;return getTicket(id)}
export async function assignTicket(id:number,agentId:number|null){if(agentId!==null){const [a]=await pool.query<RowDataPacket[]>("SELECT id FROM agents WHERE id=? AND status='ACTIVE'",[agentId]);if(!a.length)throw Object.assign(new Error("Active agent not found"),{statusCode:404})}const [r]=await pool.execute<ResultSetHeader>("UPDATE tickets SET agent_id=? WHERE id=?",[agentId,id]);if(!r.affectedRows)return null;return getTicket(id)}
export async function updateStatus(id:number,status:Status){const [r]=await pool.execute<ResultSetHeader>("UPDATE tickets SET status=? WHERE id=?",[status,id]);if(!r.affectedRows)return null;return getTicket(id)}
export async function deleteTicket(id:number){const [r]=await pool.execute<ResultSetHeader>("DELETE FROM tickets WHERE id=?",[id]);return r.affectedRows>0}
export async function dashboard(){const [counts]=await pool.query<RowDataPacket[]>(`SELECT COUNT(*) total,SUM(status='OPEN') open_count,SUM(status='IN_PROGRESS') in_progress,SUM(status='RESOLVED') resolved FROM tickets`);const [recent]=await pool.query<TicketPacket[]>(`${base} ORDER BY t.created_at DESC LIMIT 5`);const c=counts[0] as Record<string,unknown>;return {total:Number(c.total??0),open:Number(c.open_count??0),inProgress:Number(c.in_progress??0),resolved:Number(c.resolved??0),recent}}
export async function agents(){const [rows]=await pool.query<RowDataPacket[]>("SELECT id,name,email,department,status,created_at FROM agents ORDER BY name");return rows}
